---
version: '3'
services:

  # Pulsar config adapted from: https://pulsar.apache.org/docs/standalone-docker/#start-pulsar-in-docker
  pulsar:
    image: apachepulsar/pulsar:2.10.0
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    command: [ "bin/pulsar", "standalone" ]
    volumes:
      - "./pulsar-data:/pulsar/data"

  pulsar-express:
    image: bbonnin/pulsar-express
    container_name: pulsar-express
    depends_on:
      - pulsar
    ports:
      - "3000:3000"
    environment:
      - "PE_CONNECTION_URL=http://host.docker.internal:8080"