---
version: '3'
services:

  # Pulsar config adapted from: https://pulsar.apache.org/docs/standalone-docker/#start-pulsar-in-docker
  pulsar:
    image: apachepulsar/pulsar:2.10.0
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    command: [ "bin/pulsar", "standalone" ]
    # volumes:
    #   - "./pulsar/data:/pulsar/data"